<a href="https://colab.research.google.com/github/kelseymatsik/DS3001/blob/main/data_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
! git clone https://github.com/kelseymatsik/project_chd

Cloning into 'project_chd'...
remote: Enumerating objects: 13, done.
remote: Counting objects: 100% (13/13), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 13 (delta 4), reused 2 (delta 0), pack-reused 0
Receiving objects: 100% (13/13), 635.72 KiB | 1.95 MiB/s, done.
Resolving deltas: 100% (4/4), done.

In [15]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv("./project_chd/fhs_train.csv")
df.head()

,Unnamed: 0,sex,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
0,1267,1,58,1.0,0,0.0,0.0,0,0,0,220.0,143.0,104.0,29.85,75,87.0,1
1,1209,0,40,1.0,1,15.0,0.0,0,0,0,199.0,122.0,82.0,22.16,85,77.0,0
2,2050,0,52,1.0,0,0.0,0.0,0,0,0,275.0,112.0,71.0,25.68,80,NaN,0
3,1183,1,38,2.0,1,43.0,0.0,0,1,0,170.0,130.0,94.0,23.90,110,75.0,0
4,3225,0,43,1.0,0,0.0,0.0,0,0,0,202.0,124.0,92.0,21.26,75,74.0,0

In [8]:
# Renaming columns to be more intuitive
df = df.rename(columns = {'prevalentStroke': 'stroke',
                          'prevalentHyp': 'hypertensive',
                          'TenYearCHD': 'tenYearRisk'})

# Dropping 'Unnamed: 0' column
df.drop('Unnamed: 0', axis=1, inplace=True)

In [9]:
df.head()

,sex,age,education,currentSmoker,cigsPerDay,BPMeds,stroke,hypertensive,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,tenYearRisk
0,1,58,1.0,0,0.0,0.0,0,0,0,220.0,143.0,104.0,29.85,75,87.0,1
1,0,40,1.0,1,15.0,0.0,0,0,0,199.0,122.0,82.0,22.16,85,77.0,0
2,0,52,1.0,0,0.0,0.0,0,0,0,275.0,112.0,71.0,25.68,80,NaN,0
3,1,38,2.0,1,43.0,0.0,0,1,0,170.0,130.0,94.0,23.90,110,75.0,0
4,0,43,1.0,0,0.0,0.0,0,0,0,202.0,124.0,92.0,21.26,75,74.0,0

In [10]:
df.columns

Index(['sex', 'age', 'education', 'currentSmoker', 'cigsPerDay', 'BPMeds',
       'stroke', 'hypertensive', 'diabetes', 'totChol', 'sysBP', 'diaBP',
       'BMI', 'heartRate', 'glucose', 'tenYearRisk'],
      dtype='object')

In [11]:
# Setting temporary variable names
sex = df['sex']
age = df['age']
education = df['education']
currentSmoker = df['currentSmoker']
cigsPerDay = df['cigsPerDay']
BPMeds = df['BPMeds']
stroke = df['stroke']
hypertensive = df['hypertensive']
diabetes = df['diabetes']
totChol = df['totChol']
sysBP = df['sysBP']
diaBP = df['diaBP']
BMI = df['BMI']
heartRate = df['heartRate']
glucose = df['glucose']
glucose = df['glucose']

In [14]:
# Looking at value counts for each variable

for var in df.columns:
  print(df[var].value_counts())

# cigsPerDay is the number of cigarettes smoked each day, but only has values of 0 and 1
# Not sure what that means...

0    1803
1    1377
Name: sex, dtype: int64
48    139
42    139
40    138
46    137
41    136
39    125
45    125
43    116
44    116
55    113
52    113
38    112
47    107
53    104
54    103
51    101
50    100
49    100
56     93
58     91
60     90
61     87
59     86
63     85
57     84
62     75
64     66
37     63
36     60
65     50
67     31
35     30
66     29
34     14
68     10
33      5
69      4
70      2
32      1
Name: age, dtype: int64
1.0    1310
2.0     949
3.0     495
4.0     341
Name: education, dtype: int64
0    1619
1    1561
Name: currentSmoker, dtype: int64
0.0     1619
20.0     528
30.0     172
15.0     159
10.0     108
5.0       95
9.0       94
3.0       73
40.0      67
1.0       53
43.0      40
25.0      33
35.0      16
6.0       15
2.0       13
8.0       10
60.0       9
7.0        9
18.0       7
23.0       5
11.0       5
50.0       5
4.0        4
17.0       4
16.0       3
12.0       2
19.0       2
29.0       1
14.0       1
70.0       1
45.0       1
38.0       1
13.0       1
Name: cigsPerDay, dtype: int64
0.0    3050
1.0      93
Name: BPMeds, dtype: int64
0    3159
1      21
Name: stroke, dtype: int64
0    2159
1    1021
Name: hypertensive, dtype: int64
0    3097
1      83
Name: diabetes, dtype: int64
240.0    63
220.0    50
232.0    49
260.0    48
210.0    45
         ..
385.0     1
359.0     1
355.0     1
119.0     1
392.0     1
Name: totChol, Length: 243, dtype: int64
110.0    72
130.0    71
120.0    70
115.0    69
125.0    68
         ..
213.0     1
187.5     1
85.0      1
201.0     1
169.5     1
Name: sysBP, Length: 229, dtype: int64
80.0     198
82.0     106
84.0     102
85.0     102
81.0      98
        ...
115.5      1
135.0      1
110.5      1
129.0      1
122.5      1
Name: diaBP, Length: 139, dtype: int64
23.48    17
22.91    15
22.54    12
23.09    12
25.09    11
         ..
17.65     1
29.46     1
32.81     1
23.83     1
26.78     1
Name: BMI, Length: 1234, dtype: int64
75     428
80     273
70     226
60     174
85     170
      ...
51       1
46       1
97       1
47       1
130      1
Name: heartRate, Length: 70, dtype: int64
75.0     147
77.0     126
73.0     119
80.0     117
70.0     113
        ...
348.0      1
119.0      1
320.0      1
136.0      1
186.0      1
Name: glucose, Length: 130, dtype: int64
0    2693
1     487
Name: tenYearRisk, dtype: int64

In [44]:
# Check for missings
for var in df.columns:
    missing_percentage = df[var].isna().sum() / len(df) * 100
    print(f"{var}: {missing_percentage:.2f}% missing")

print('total missing: ', df.isna().sum().sum(),  '\n', 'total % missing: ', (df.isna().sum().sum()/len(df) * 100))
# Overall, the data frame does not have many missings

sex: 0.00% missing
age: 0.00% missing
education: 2.67% missing
currentSmoker: 0.00% missing
cigsPerDay: 0.75% missing
BPMeds: 1.16% missing
stroke: 0.00% missing
hypertensive: 0.00% missing
diabetes: 0.00% missing
totChol: 1.23% missing
sysBP: 0.00% missing
diaBP: 0.00% missing
BMI: 0.47% missing
heartRate: 0.00% missing
glucose: 8.96% missing
tenYearRisk: 0.00% missing
total missing:  485
 total % missing:  15.251572327044025

In [45]:
# Examining missings
BPMeds_missing = df[df['BPMeds'].isnull()]
# len(BPMeds_missing)
totChol_missing = df[df['totChol'].isnull()]
BPMeds_missing

,sex,age,education,currentSmoker,cigsPerDay,BPMeds,stroke,hypertensive,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,tenYearRisk
110,1,57,4.0,0,0.0,NaN,0,1,0,195.0,162.0,108.0,32.65,85,73.0,0
156,0,52,3.0,1,9.0,NaN,0,0,0,275.0,102.0,70.5,20.40,65,NaN,0
181,0,56,2.0,0,0.0,NaN,0,0,0,220.0,126.5,74.5,28.30,82,80.0,1
290,1,51,4.0,0,0.0,NaN,0,0,0,154.0,98.0,66.0,22.86,63,82.0,0
454,0,59,1.0,1,3.0,NaN,0,1,0,201.0,145.0,88.0,39.91,65,89.0,0
574,0,55,1.0,0,0.0,NaN,0,1,0,325.0,155.0,90.0,26.27,68,72.0,1
676,0,67,2.0,0,0.0,NaN,0,0,0,261.0,117.0,63.0,22.55,75,83.0,0
905,0,40,2.0,0,0.0,NaN,0,0,0,157.0,131.0,85.0,27.38,95,78.0,0
937,0,39,2.0,0,0.0,NaN,0,0,0,242.0,113.0,85.0,25.54,85,104.0,0
943,0,41,2.0,1,20.0,NaN,0,0,0,220.0,126.0,78.0,20.70,86,79.0,0
949,1,54,4.0,1,30.0,NaN,0,1,0,234.0,152.5,80.0,23.50,75,75.0,0
980,0,65,1.0,0,0.0,NaN,1,1,0,290.0,144.0,64.0,21.41,58,145.0,1
1087,0,60,1.0,0,0.0,NaN,0,1,0,273.0,176.0,84.0,22.17,66,79.0,0
1113,0,56,1.0,0,0.0,NaN,0,1,0,391.0,126.0,84.0,24.83,80,78.0,0
1224,0,57,1.0,0,0.0,NaN,0,0,0,372.0,122.0,80.0,21.02,65,81.0,0
1518,0,41,1.0,0,0.0,NaN,0,0,0,179.0,121.0,83.0,23.04,66,90.0,0
1520,0,60,1.0,0,0.0,NaN,0,1,0,231.0,174.0,110.0,25.05,85,82.0,0
1553,0,48,2.0,1,20.0,NaN,0,0,0,248.0,131.0,72.0,22.00,84,86.0,0
1596,0,62,3.0,0,0.0,NaN,0,1,0,294.0,139.0,78.0,21.11,85,79.0,0
1671,0,68,1.0,0,0.0,NaN,0,1,0,258.0,139.0,74.0,26.58,85,75.0,1
1725,0,37,3.0,0,0.0,NaN,0,0,0,145.0,105.0,73.0,23.44,58,80.0,0
1790,0,59,1.0,1,20.0,NaN,0,0,0,225.0,110.0,64.0,28.10,66,64.0,0
1827,0,41,1.0,1,20.0,NaN,0,0,0,203.0,120.0,70.0,21.26,80,63.0,0
1900,0,56,1.0,1,9.0,NaN,0,1,0,320.0,142.0,84.0,27.90,74,95.0,1
2080,1,50,4.0,1,9.0,NaN,0,0,0,296.0,119.0,90.0,23.55,75,69.0,1
2191,1,58,1.0,1,30.0,NaN,0,0,0,200.0,144.0,90.0,24.90,75,76.0,0
2215,0,52,1.0,0,0.0,NaN,0,1,0,252.0,208.0,136.0,25.79,92,82.0,0
2290,0,57,1.0,0,0.0,NaN,0,0,0,262.0,129.0,75.0,23.67,70,95.0,0
2335,0,65,2.0,0,0.0,NaN,0,1,0,270.0,165.0,98.0,21.66,62,92.0,1
2439,1,45,3.0,1,40.0,NaN,0,0,0,278.0,135.0,84.0,23.79,75,79.0,1
2460,0,66,1.0,0,0.0,NaN,0,1,1,203.0,205.0,83.0,28.27,75,118.0,1
2742,0,44,3.0,1,20.0,NaN,0,0,0,213.0,115.0,72.5,21.16,80,89.0,0
2752,0,47,3.0,1,9.0,NaN,0,0,0,221.0,127.5,75.0,23.78,69,73.0,0
2796,1,46,1.0,1,30.0,NaN,0,1,0,253.0,147.0,85.0,30.62,100,75.0,0
2819,0,67,1.0,1,6.0,NaN,0,0,0,NaN,120.0,67.0,32.77,86,NaN,0
2847,0,66,1.0,0,0.0,NaN,0,1,0,235.0,151.0,91.0,30.86,78,87.0,0
3167,0,61,1.0,0,0.0,NaN,0,0,0,218.0,148.0,80.0,37.04,82,78.0,0